server:
  port: 8000
spring:
  application:
    name: short-link-gateway-service
  profiles:
    active: prod
    # active: dev
  data:
    redis:
      host: 47.113.145.127
      port: 6379
      password: S8A1qmLF7nhGSvxEDZkeKw==