spring:
  cloud:
    gateway:
      routes:
        - id: short-link-admin-service
          uri: lb://short-link-admin-service/api/short/link/admin/**
          predicates:
            - Path=/api/short/link/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short/link/admin/v1/user/login
                  - /api/short/link/admin/v1/user/has-username

        - id: short-link-project-service
          uri: lb://short-link-project-service/api/short/link/project/**
          predicates:
            - Path=/api/short/link/project/**
          filters:
            - name: TokenValidate
