spring:
  data:
    redis:
      port: 6379
      host: 47.113.145.127
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 47.94.0.36:8848
  datasource:
    # 新版本实现了对 JDBC Driver 的自定义功能，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingsphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml