server:
  port: 8002
spring:
  application:
    name: short-link-admin-service
  profiles:
    active: prod
  datasource:
    # 新版本实现了对 JDBC Driver 的自定义功能，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingsphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml
  data:
    redis:
      port: 6379
      host: 47.113.145.127
      password: S8A1qmLF7nhGSvxEDZkeKw==
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: false
    time-window: 1
    max-access-count: 50