server:
  port: 8002
spring:
  application:
    name: short-link-admin-service
  profiles:
    active: dev
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: false
    time-window: 1
    max-access-count: 50