spring:
  data:
    redis:
      port: 6379
      host: 172.24.23.38
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.23.38:8848
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml