server:
  port: 8003

spring:
  application:
    name: short-link-aggregation-service
  profiles:
    active: prod
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      port: 6379
      host: 47.113.145.127
      password: S8A1qmLF7nhGSvxEDZkeKw==
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml


short-link:
  group:
    max-num: 20
  flow-limit:
    enable: false
    time-window: 1
    max-access-count: 50
  domain:
    default: tiny.intbeast.top
  stats:
    locale:
      amap-key: a336bb745b866b677786215eb3d947c6
  goto-domain:
    # 白名单，目前关闭
    white-list:
      enable: false
      names: '淘宝,天猫,知乎,京东,CSDN'
      details:
        - taobao.com
        - tmall.com
        - zhihu.com
        - csdn.net

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

aggregation:
  remote-url: http://127.0.0.1:${server.port}
