server:
  port: 8001
spring:
  application:
    name: short-link-project-service
  profiles:
    active: dev
  mvc:
    view:
      prefix: /templates/
      suffix: .html
#    sentinel:
#      transport:
#        client-ip: localhost:8686
#        port: 8719
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

short-link:
  domain:
    default: tinybridge.intbeast.top
  stats:
    locale:
      amap-key: a336bb745b866b677786215eb3d947c6
  goto-domain:
    # 白名单，目前关闭
    white-list:
      enable: false
      names: '淘宝,天猫,知乎,京东,CSDN'
      details:
        - taobao.com
        - tmall.com
        - zhihu.com
        - csdn.net
