server:
  port: 8001
spring:
  datasource:
    # 新版本实现了对 JDBC Driver 的自定义功能，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingsphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
#      username: root
#      password: ginwithouta
#      url: jdbc:mysql://172.23.236.240:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      hikari:
#        connection-test-query: select 1
#        connection-timeout: 20000
#        idle-timeout: 300000
#        maximum-pool-size: 5
#        minimum-idle: 5
  data:
    redis:
      port: 6379
      host: 172.20.253.81
      password: 123456
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    sentinel:
      transport:
        client-ip: localhost:8686
        port: 8719
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

short-link:
  domain:
    default: tinybridge.intbeast.top:8001
  statistics:
    locale:
      amap-key: a336bb745b866b677786215eb3d947c6
  goto-domain:
    # 白名单，目前关闭
    white-list:
      enable: false
      names: '淘宝,天猫,知乎,京东,CSDN'
      details:
        - taobao.com
        - tmall.com
        - zhihu.com
        - csdn.net
