server:
  port: 8001
spring:
  application:
    name: short-link-project-service
  datasource:
    # 新版本实现了对 JDBC Driver 的自定义功能，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # shardingsphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      port: 6379
      host: 47.113.145.127
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.145.127:8848
#    sentinel:
#      transport:
#        client-ip: localhost:8686
#        port: 8719
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

short-link:
  domain:
    default: tinybridge.intbeast.top
  stats:
    locale:
      amap-key: a336bb745b866b677786215eb3d947c6
  goto-domain:
    # 白名单，目前关闭
    white-list:
      enable: false
      names: '淘宝,天猫,知乎,京东,CSDN'
      details:
        - taobao.com
        - tmall.com
        - zhihu.com
        - csdn.net
